services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile # Assuming you have a Dockerfile
    ports:
      - "5173:5173" # Map host port 3001 to container's 3000 (Vite default)
    volumes:
      - ./web-client:/app # Mount your project's src folder
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file watching on some systems
    command: npm run dev # Start Vite's development server
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'Joseph1356'
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql:Z
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  backend:
    build:
      context: ./backend
    ports:
      - 8060:8060
volumes:
  mariadb:
networks:
  default:
      name: "intune-depot-app"
      external: true